server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:garage-db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    # IMPORTANT: Kafka est sur WSL, donc on met l'IP WSL (pas localhost)
    bootstrap-servers: 172.23.106.71:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: garage-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.renault.garage.messaging.event
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.renault.garage.messaging.event.VehicleCreatedEvent
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
app:
  kafka:
    topics:
      vehicleCreated: vehicle-created